# -*- coding: utf-8 -*-
"""Reddit_Posts_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1znu7EiBg_glybBZ7zT-uY7MA-Ofc2QlQ

Reddit Post NFSW Classification Project

Importing the necessary libararies
"""

!pip install pandasql

import numpy as np
import pandas as pd
import spacy
import nltk
import re
import json
from nltk.corpus import stopwords
import pandas as pd
from pandasql import sqldf
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, classification_report

from google.colab import drive
drive.mount('/content/drive')

"""Reading Data and Initial Exploration"""

file_path='/content/drive/MyDrive/Projects/reddit_data.csv'
df = pd.read_csv(file_path)
print("the data shape is:",df.shape)
df.head(10)

df.describe()

df.isnull().sum()

"""Basic information:
The data shape is 1,93,091,i.e. 193k rows are there. This is moderately big dataset.

So the reddit data has the following columns:

(1) id: this represents a unique id for each post.

(2) title: each reddit post contains a title, this is the title text.

(3) score: each reddit post can be upvoted or downvoted. And thereby receives a score. This is that score.

(4) author: this is basically user name.

(5) author_flair_text: Need to know exactly what does it represent. We will inspect the data first and check in other notebooks too.

(6) removed_by: this is removed by what option. i.e. if the post is eventually removed, who removed it. This is a very interesting source of data.

(7) created_utc: when was this post created in utc timing but it is in unix epoch format. We need to transform it into normal date time to work on it.

(8) full_link: what is the full_link for the reddit post. This url will contain reddit's domain, subreddit and other informations. Need to parse the link to create subreddit and other different informations.

(9)num_comments: this is total number of comments which were seen in the post.

(10) over_18: this is basically the NSFW tag in reddit. Denotes whether the post contains something adult or not.

Performing EDA using Panda-SQL Library
"""

pysqldf = lambda q: sqldf(q, globals())

# Just Reading the data using psql
q1 = "SELECT * FROM df LIMIT 10;"
pysqldf(q1)

#Count of Posts per author
q2 = """
SELECT author, COUNT(*) AS total_posts
FROM df
GROUP BY author
ORDER BY total_posts DESC;
"""
pysqldf(q2)

#Average score per author flair
q3 = """
SELECT author_flair_text, AVG(score) AS avg_score, COUNT(*) AS num_posts
FROM df
WHERE author_flair_text IS NOT NULL
GROUP BY author_flair_text
ORDER BY avg_score DESC;
"""
pysqldf(q3)

# Posts with above-average score (CTE example)
q4 = """
WITH avg_score_cte AS (
    SELECT AVG(score) AS avg_score FROM df
)
SELECT id, title, author, score
FROM df, avg_score_cte
WHERE score > avg_score_cte.avg_score
ORDER BY score DESC;
"""
pysqldf(q4)

#Distribution of NSFW (over_18) posts

q5 = """
SELECT over_18, COUNT(*) AS post_count,
       ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM df), 2) AS percent
FROM df
GROUP BY over_18;
"""
pysqldf(q5)

# Total posts removed + percentage by moderator
q6a = """
WITH total_posts AS (
    SELECT COUNT(*) AS total_count FROM df
),
removed_summary AS (
    SELECT
        removed_by,
        COUNT(*) AS total_removed
    FROM df
    WHERE removed_by IS NOT NULL
    GROUP BY removed_by
)
SELECT
    r.removed_by,
    r.total_removed,
    ROUND(100.0 * r.total_removed / t.total_count, 2) AS percent_removed
FROM removed_summary r, total_posts t
ORDER BY percent_removed DESC;
"""
pysqldf(q6a)

#NSFW vs SFW deletion distribution
q6b ='''
WITH deletion_stats AS (
    SELECT
        over_18,
        CASE WHEN removed_by IS NOT NULL THEN 'Deleted' ELSE 'Not Deleted' END AS deletion_status,
        COUNT(*) AS post_count
    FROM df
    GROUP BY over_18, deletion_status
),
total_counts AS (
    SELECT SUM(post_count) AS total_posts FROM deletion_stats
)
SELECT
    d.over_18,
    d.deletion_status,
    d.post_count,
    ROUND(100.0 * d.post_count / t.total_posts, 2) AS percent_of_total
FROM deletion_stats d, total_counts t
ORDER BY d.over_18, d.deletion_status;
'''
pysqldf(q6b)

#Top posts by number of comments (Window function)
q7 ='''
SELECT id, title, author, num_comments,
       RANK() OVER (ORDER BY num_comments DESC) AS comment_rank
FROM df
ORDER BY num_comments DESC
LIMIT 10;
'''
pysqldf(q7)

#Award insights
q9 ='''
SELECT author, SUM(total_awards_received) AS total_awards,
       AVG(total_awards_received) AS avg_awards
FROM df
GROUP BY author
HAVING total_awards > 0
ORDER BY total_awards DESC;
'''
pysqldf(q9)

#CTE + Window Function combined: Top 3 posts per author
q10 ='''
WITH ranked_posts AS (
    SELECT author, id, title, score,
           ROW_NUMBER() OVER (PARTITION BY author ORDER BY score DESC) AS rn
    FROM df
)
SELECT * FROM ranked_posts WHERE rn <= 3;
'''
pysqldf(q10)

"""Preprocessing Data"""

df.isnull().sum()

df.dropna(subset=["title"],inplace=True)
df.author_flair_text.fillna("",inplace=True)
df.removed_by.fillna("Not Removed",inplace=True)
df.drop(columns=["awarders","created_utc"],inplace=True)

df.isnull().sum()

# Remove NaN or invalid values just in case
df['total_awards_received'] = pd.to_numeric(df['total_awards_received'], errors='coerce')
df_clean = df.dropna(subset=['total_awards_received'])

plt.figure(figsize=(8,5))
sns.histplot(df_clean['total_awards_received'], bins=10, kde=True)
plt.title('Distribution of Total Awards Received')
plt.xlabel('Total Awards Received')
plt.ylabel('Count')
plt.grid(alpha=0.3)
plt.show()

df.total_awards_received.fillna(0,inplace=True)

df.isnull().sum()

"""Further Analysis"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Convert categorical to numeric if needed
df['over_18'] = df['over_18'].astype(int)
# df['is_deleted'] = df['removed_by'].notnull().astype(int)

# Select numeric columns for correlation
num_cols = ['score', 'num_comments', 'total_awards_received', 'over_18']
corr = df[num_cols].corr(method='pearson')
corr

plt.figure(figsize=(7,5))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title("Pearson Correlation: Post Ratings, Deletions, and Flags")
plt.show()

sns.pairplot(df[num_cols], diag_kind='kde')
plt.suptitle("Pairwise Relationships Among Key Variables", y=1.02)
plt.show()

from wordcloud import WordCloud, STOPWORDS

text = " ".join(df['title'].dropna().astype(str))
wc = WordCloud(width=1000, height=500,
               background_color='white',
               stopwords=set(STOPWORDS),
               colormap='plasma').generate(text)

plt.figure(figsize=(10,5))
plt.imshow(wc, interpolation='bilinear')
plt.axis('off')
plt.title('Word Cloud of Post Titles')
plt.show()

from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt

# Separate text for SFW and NSFW
sfw_text = " ".join(df[df['over_18'] == False]['title'].dropna().astype(str))
nsfw_text = " ".join(df[df['over_18'] == True]['title'].dropna().astype(str))

# Define common WordCloud settings
wc_params = {
    "width": 800,
    "height": 500,
    "background_color": "white",
    "stopwords": set(STOPWORDS),
    "colormap": "viridis"
}

# Generate both word clouds
wc_sfw = WordCloud(**wc_params).generate(sfw_text)
wc_nsfw = WordCloud(**wc_params).generate(nsfw_text)

# Plot side by side
plt.figure(figsize=(16, 6))

plt.subplot(1, 2, 1)
plt.imshow(wc_sfw, interpolation='bilinear')
plt.axis('off')
plt.title('Word Cloud — SFW Posts (over_18 = False)', fontsize=14)

plt.subplot(1, 2, 2)
plt.imshow(wc_nsfw, interpolation='bilinear')
plt.axis('off')
plt.title('Word Cloud — NSFW Posts (over_18 = True)', fontsize=14)

plt.tight_layout()
plt.show()

# Download resources if not already done
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

# Import PorterStemmer
from nltk.stem import PorterStemmer # Added this import statement

# Sample text column
texts = df['title'].dropna().astype(str)

# Imputation (replace NaN or missing values)
texts = texts.fillna("")

# Text Cleaning (remove punctuation, numbers, special chars)
texts = texts.apply(lambda x: re.sub(r'[^a-zA-Z\s]', '', x.lower()))

# Tokenization
texts_tokenized = texts.apply(nltk.word_tokenize)

# Stopword Removal
stop_words = set(stopwords.words('english'))
stop_words.add("oc") # Added 'oc' to the stopwords set
texts_no_stop = texts_tokenized.apply(lambda tokens: [w for w in tokens if w not in stop_words]) # Modified this line

# Stemming
stemmer = PorterStemmer()
texts_stemmed = texts_no_stop.apply(lambda tokens: [stemmer.stem(w) for w in tokens])

# Join tokens back for TF-IDF
texts_ready = texts_stemmed.apply(lambda tokens: " ".join(tokens))

# TF-IDF Vectorization
tfidf = TfidfVectorizer(max_features=1000)
X_tfidf = tfidf.fit_transform(texts_ready)

# Split for modeling

# Target column for stratification
stratify_col = df['over_18'].astype(int)

# Perform stratified split
X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf,           # TF-IDF features
    df['over_18'],  # target
    test_size=0.3,
    random_state=42,
    stratify=stratify_col  # ensures same proportion of over_18 in train/test
)

# Optional check
print("Train set over_18 distribution:")
print(y_train.value_counts(normalize=True)) # Corrected for sparse matrix output

print("\nTest set over_18 distribution:")
print(y_test.value_counts(normalize=True)) # Corrected for sparse matrix output

# ----------------------------------------
# Decision Tree Classifier
# ----------------------------------------
dt = DecisionTreeClassifier(max_depth=10)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)

# Metrics for Decision Tree
acc_dt = accuracy_score(y_test, y_pred_dt)
prec_dt = precision_score(y_test, y_pred_dt)
rec_dt = recall_score(y_test, y_pred_dt)
f1_dt = f1_score(y_test, y_pred_dt)

print("----- Decision Tree Performance -----")
print(f"Accuracy : {acc_dt:.2f}")
print(f"Precision: {prec_dt:.2f}")
print(f"Recall   : {rec_dt:.2f}")
print(f"F1-Score : {f1_dt:.2f}\n")

# ----------------------------------------
# Random Forest Classifier
# ----------------------------------------
rf = RandomForestClassifier(n_estimators=300, max_depth=50)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

# Metrics for Random Forest
acc_rf = accuracy_score(y_test, y_pred_rf)
prec_rf = precision_score(y_test, y_pred_rf)
rec_rf = recall_score(y_test, y_pred_rf)
f1_rf = f1_score(y_test, y_pred_rf)

print("----- Random Forest Performance -----")
print(f"Accuracy : {acc_rf:.2f}")
print(f"Precision: {prec_rf:.2f}")
print(f"Recall   : {rec_rf:.2f}")
print(f"F1-Score : {f1_rf:.2f}\n")

# Full classification report for Random Forest
print("Detailed Classification Report (Random Forest):")
print(classification_report(y_test, y_pred_rf))

# Example structured schema
RESPONSE_SCHEMA = {
    "type": "object",
    "properties": {
        "nsfw_flag": {
            "type": "string",
            "enum": ["yes", "no"]
        }
    },
    "required": ["nsfw_flag"]
}

# Optional: System prompt to guide model
SYSTEM_PROMPT = """
You are an assistant that determines whether a post is NSFW 18+ sexually explicit posts based on its title.
Return the output as JSON matching the schema}.
"""

!pip install -q google-generativeai
import google.generativeai as genai
from google import genai
from google.genai.types import GenerateContentConfig, ThinkingConfig

# Set your API key
api_key="YOUR_NEW_API_KEY_HERE" # <--- REPLACE THIS WITH YOUR NEW API KEY
client = genai.Client(api_key=api_key)
model = client.models.generate_content

def call_model(title_text, config):
  response = model(model="gemini-2.0-flash", contents=[title_text], config=config)
  return response.text

def process_title(title_text):
    config = {
        "response_mime_type": "application/json",
        "response_schema": RESPONSE_SCHEMA,
        "system_instruction": SYSTEM_PROMPT,
        "thinking_config": {"thinking_budget": 0}  # optional
    }

    raw_response = call_model(title_text,config)
    print(raw_response)
    try:
        parsed = json.loads(raw_response)  # parse JSON response
        nsfw_flag = parsed.get("nsfw_flag", "no")  # default to "no" if missing
    except Exception as e:
        nsfw_flag = "no"  # fallback if model fails
    return nsfw_flag

df_sample=df.iloc[:10,:]
print(df_sample.head())
df_sample['nsfw_flag'] = df_sample['title'].apply(process_title)
print(df_sample[['title','nsfw_flag']].head())